server:
  port: 80
  context-path: /qgyblog
#jdbc的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qgyblog
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 127.0.0.1
#    password: root
    # Redis数据库索引（默认为0）
    database: 0
    port: 6379
    pool:
#连接池最大连接数（使用负值表示没有限制） 默认8
      max-active: 8
  freemarker:
    content-type: text/html
    cache: false
    check-template-location: true
    suffix: .html
    charset: utf-8

#  thymeleaf:
#    content-type: text/html
#    cache: false
#    mode: LEGACYHTML5